const test=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
function env(){let job={request:'22222222-3333-4444-8555-666666666666',conversation:'aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee',tabId:7,status:'watching',files:[]};let message;let change;let determine;let fail=false;let queued;const downloads=[];const posts=[];const events={addListener:()=>{}};
 const chrome={storage:{local:{get:async()=>({job:structuredClone(job)}),set:async(v)=>{job=structuredClone(v.job);}}},alarms:{create:()=>{},onAlarm:events},runtime:{onMessage:{addListener:f=>message=f},onStartup:events},action:{setBadgeText:async()=>{}},downloads:{download:async x=>{if(fail)throw Error('blocked');downloads.push(x);return downloads.length;},search:async({id})=>[{id,state:'complete'}],onDeterminingFilename:{addListener:f=>determine=f},onChanged:{addListener:f=>change=f}}};
 const c=vm.createContext({chrome,URL,importScripts:()=>{},RELAY:{url:'http://local',token:'test'},fetch:async(url,options)=>{if(options.body)posts.push(JSON.parse(options.body));return {ok:true,json:async()=>({received:true,receipt:'test-receipt',jobs:queued||[{request:job.request,conversation:job.conversation}]})};},module:{exports:{}},Set});vm.runInContext(fs.readFileSync(__dirname+'/extension/background.js','utf8'),c);
 return {setPending:value=>queued=value,api:c.module.exports,get job(){return job},downloads,posts,determine:(item)=>new Promise(r=>determine(item,r)),setFail:()=>fail=true,send:(m,s)=>new Promise(r=>message(m,s,r))};}
const link='https://chatgpt.com/backend-api/estuary/content?id=file_abc&fn=demo.html&sig=private';
const sender={tab:{id:7},url:'https://chatgpt.com/c/aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee'};
function packet(e){return{type:'artifact',request:e.job.request,conversation:e.job.conversation,links:[{url:link}]};}
test('accept only supported same-origin attachment URLs',()=>{const {api}=env();assert.equal(api.allowed(link),true);for(const u of ['https://evil.test/a','javascript:alert(1)','https://chatgpt.com/backend-api/other?id=file_abc'])assert.equal(api.allowed(u),false);});
test('wrong tab cannot trigger any download',async()=>{const e=env();await e.send(packet(e),{...sender,tab:{id:8}});assert.equal(e.downloads.length,0);});
test('completed artifact downloads then receipt; duplicate event ignored',async()=>{const e=env();await e.send(packet(e),sender);assert.equal(e.job.status,'received');assert.equal(e.downloads.length,1);assert.equal(e.posts.length,1);await e.send(packet(e),sender);assert.equal(e.downloads.length,1);});
test('blocked download never generates success receipt',async()=>{const e=env();e.setFail();await e.send(packet(e),sender);assert.equal(e.job.status,'failed');assert.equal(e.downloads.length,0);});
test('missing attachment keeps job pending',async()=>{const e=env();await e.send({...packet(e),links:[]},sender);assert.equal(e.job.status,'watching');assert.equal(e.downloads.length,0);});
test('unsafe filename is sanitized',()=>{const {api}=env();assert.equal(api.nameOf(link.replace('demo.html','..%2F..%2Fbad.exe'),0).includes('/'),false);});
test('button path arms once and matches the actual download filename',async()=>{const e=env();const p={...packet(e),type:'button-download',names:['demo.html']};assert.equal((await e.send(p,sender)).click,true);assert.equal(e.job.status,'awaiting_browser_download');assert.equal((await e.send(p,sender)).click,undefined);assert.equal(e.downloads.length,0);const suggestion=await e.determine({id:42,url:link});assert.match(suggestion.filename,/demo.html$/);await new Promise(r=>setImmediate(r));assert.equal(e.job.status,'received');assert.equal(e.downloads.length,0);assert.equal(e.posts.length,1);});
test('unrelated download cannot complete the selected request',async()=>{const e=env();await e.send({...packet(e),type:'button-download',names:['demo.html']},sender);assert.equal(await e.determine({id:42,url:link.replace('demo.html','other.html')}),undefined);assert.equal(e.job.status,'awaiting_browser_download');assert.equal(e.downloads.length,0);});
test('plain text delivers without any browser download',async()=>{const e=env();await e.send({...packet(e),type:'text-result',prompt:'request',text:'answer',attachmentExpected:false},sender);assert.equal(e.job.status,'received');assert.equal(e.posts.length,1);assert.equal(e.posts[0].text,'answer');assert.equal(e.downloads.length,0);});
test('jobs registry automatically supplies this conversation request',async()=>{const e=env();const result=await e.send({type:'jobs',conversation:e.job.conversation},sender);assert.equal(result.job.request,e.job.request);assert.equal(e.downloads.length,0);});



test('another project cannot overwrite an active download or watch',async()=>{const e=env();const original=e.job.request;const chat='aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee';const result=await e.send({type:'jobs',conversation:chat},{tab:{id:9},url:'https://chatgpt.com/c/'+chat});assert.equal(result.job,null);assert.equal(e.job.request,original);});

test('stale cached job does not block a newly registered project',async()=>{const e=env();const chat='aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee';e.setPending([{request:'bbbbbbbb-cccc-dddd-eeee-ffffffffffff',conversation:chat}]);const result=await e.send({type:'jobs',conversation:chat},{tab:{id:9},url:'https://chatgpt.com/c/'+chat});assert.equal(result.job.conversation,chat);assert.equal(e.job.tabId,9);});
